
services:
  fsl: 
    build: 
      context: ./fsl
      dockerfile: dockerfile
    image: fsl/parkinson_pipeline
  pipeline:
    build:
      context: ../
      dockerfile: Docker/python_pipeline/dockerfile
    image: python/parkinson_pipeline
