FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    gnupg \
    software-properties-common \
    python3 \
    python3-pip && \
    apt-get install -y git build-essential cmake zlib1g-dev  &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget -O- https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py | python3 - -d /usr/local/fsl 

ENV FSLDIR=/usr/local/fsl
ENV PATH=${FSLDIR}/bin:$PATH
ENV FSLOUTPUTTYPE=NIFTI_GZ
ENV LD_LIBRARY_PATH=${FSLDIR}/lib:$LD_LIBRARY_PATH

RUN apt-get update && apt-get install -y jq

RUN apt-get install -y coreutils

RUN ln -sf /bin/bash /bin/sh 

#Bash is better


COPY pre.sh /app/pre.sh

RUN chmod 777 /app/pre.sh

#IMPORTANTE RECORDAR CAMBIAR PRE.SH A LF
ENTRYPOINT ["app/pre.sh"]


# Para mantener el contenedor corriendo




